export * from './exam.model';
export * from './i-answer-row.interface';
export * from './i-config.interface';
export * from './i-deactivate-component.interface';
export * from './i-exam-question.interface';
export * from './i-question.interface';
export * from './i-question-row.interface';
export * from './i-sync.interface';
export * from './question.model';
